In [1]:
import numpy as np

# Завдання на лабораторну роботу

## Завдання 1.
Задано 2 одновимірних масиви. Виконайте з ними всі арифметичні операції. Використовуючи метод конкатенації (об’єднання) масивів створіть новий масив з двох попередніх і знайдіть максимальний, мінімальний елемент, суму елементів та їх добуток.

## Завдання 2.
Задано одновимірний масив із 15 елементів. Сформувати новий масив в якому кожен елемент заданого масиву зменшити на середнє значення та відсортувати отриманий масив за зростанням.

## Завдання 3.
Задано одновимірний масив з 20 елементів. Для ініціалізації використайте функцію random(). Перетворіть його у двовимірний. Кожен елемент масиву збільшити на 10.

## Завдання 4.
Задано двовимірний масив цілих чисел в діапазоні від -15 до 15. Створіть новий масив в якому всі числа менші 0 замініть на -1, більші 0 - на 1.

## Завдання 5.
Виконайте наступні операції над матрицями:
$
2\left( A+B \right)\left( 2B-A \right)
$

$
A=\left( \begin{matrix}
   2 & 3 & -1  \\
   4 & 5 & 2  \\
   -1 & 0 & 7  \\
\end{matrix} \right)
$
 $
 B=\left( \begin{matrix}
   -1 & 0 & 5  \\
   0 & 1 & 3  \\
   2 & -2 & 4  \\
\end{matrix} \right)$

## Завдання 6
Розв'яжіть систему лінійних рівнянь

$\left\{ \begin{align}
  & {{x}_{1}}+{{x}_{2}}+2{{x}_{3}}+3{{x}_{4}}=1 \\
 & 3{{x}_{1}}-{{x}_{2}}-2{{x}_{3}}-2{{x}_{4}}=-4 \\
 & 2{{x}_{1}}-3{{x}_{2}}-{{x}_{3}}-{{x}_{4}}=-6 \\
 & {{x}_{1}}+2{{x}_{2}}+3{{x}_{3}}-{{x}_{4}}=-4 \\
\end{align} \right.$




## Завдання 1


In [2]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

In [3]:
sum_arrays = array1 + array2
diff_arrays = array1 - array2
prod_arrays = array1 * array2
div_arrays = array1 / array2

In [6]:
sum_arrays

array([ 7,  9, 11, 13, 15])

In [4]:
concatenated_array = np.concatenate((array1, array2))

In [5]:
concatenated_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
max_element = np.max(concatenated_array)
min_element = np.min(concatenated_array)
sum_elements = np.sum(concatenated_array)
prod_elements = np.prod(concatenated_array)

In [9]:
max_element

np.int64(10)

In [10]:
min_element

np.int64(1)

## Завдання 2

In [33]:
array = np.random.randint(1, 100, 15)

In [34]:
array

array([44, 59, 40,  6, 83, 91, 29, 23, 92, 70, 76, 94, 27, 60, 57],
      dtype=int32)

In [35]:
mean_value = np.mean(array)

In [36]:
mean_value

np.float64(56.733333333333334)

In [37]:
new_array = array - mean_value

In [38]:
new_array

array([-12.73333333,   2.26666667, -16.73333333, -50.73333333,
        26.26666667,  34.26666667, -27.73333333, -33.73333333,
        35.26666667,  13.26666667,  19.26666667,  37.26666667,
       -29.73333333,   3.26666667,   0.26666667])

In [39]:
sorted_array = np.sort(new_array)

In [40]:
sorted_array

array([-50.73333333, -33.73333333, -29.73333333, -27.73333333,
       -16.73333333, -12.73333333,   0.26666667,   2.26666667,
         3.26666667,  13.26666667,  19.26666667,  26.26666667,
        34.26666667,  35.26666667,  37.26666667])

## Завдання 3

In [41]:
array = np.random.random(20)


In [42]:
array

array([0.79505635, 0.69726896, 0.91766802, 0.57074862, 0.72715858,
       0.32302134, 0.62217927, 0.19935498, 0.61211705, 0.80990445,
       0.86487376, 0.64091553, 0.79807598, 0.44159571, 0.94156656,
       0.58215004, 0.26897919, 0.78418539, 0.03691574, 0.873884  ])

In [43]:
array_2d = array.reshape(4, 5)

In [44]:
array_2d

array([[0.79505635, 0.69726896, 0.91766802, 0.57074862, 0.72715858],
       [0.32302134, 0.62217927, 0.19935498, 0.61211705, 0.80990445],
       [0.86487376, 0.64091553, 0.79807598, 0.44159571, 0.94156656],
       [0.58215004, 0.26897919, 0.78418539, 0.03691574, 0.873884  ]])

In [45]:
array_2d = array_2d + 10

In [46]:
array_2d

array([[10.79505635, 10.69726896, 10.91766802, 10.57074862, 10.72715858],
       [10.32302134, 10.62217927, 10.19935498, 10.61211705, 10.80990445],
       [10.86487376, 10.64091553, 10.79807598, 10.44159571, 10.94156656],
       [10.58215004, 10.26897919, 10.78418539, 10.03691574, 10.873884  ]])

## Завдання 4

In [47]:
array_2d = np.random.randint(-15, 16, (5, 5))

In [48]:
array_2d

array([[  9,  10,   5,  -1,  12],
       [  6,  -4, -12, -14,  -2],
       [ -2,  -4,  -1,  15, -15],
       [ 12,  -3,   3,  11,  -5],
       [  6,   2,  -1,   2,  -9]], dtype=int32)

In [49]:
new_array_2d = np.where(array_2d < 0, -1, np.where(array_2d > 0, 1, 0))

In [50]:
new_array_2d

array([[ 1,  1,  1, -1,  1],
       [ 1, -1, -1, -1, -1],
       [-1, -1, -1,  1, -1],
       [ 1, -1,  1,  1, -1],
       [ 1,  1, -1,  1, -1]])

## Завдання 5

In [51]:
A = np.array([[2, 3, -1],
              [4, 5, 2],
              [-1, 0, 7]])

B = np.array([[-1, 0, 5],
              [0, 1, 3],
              [2, -2, 4]])

In [52]:
A

array([[ 2,  3, -1],
       [ 4,  5,  2],
       [-1,  0,  7]])

In [55]:
B

array([[-1,  0,  5],
       [ 0,  1,  3],
       [ 2, -2,  4]])

In [53]:
result = 2 * np.dot(A + B, 2 * B - A)


In [54]:
result

array([[   8,  -56,   54],
       [ -30, -100,  146],
       [ 118,  -82,   28]])

## Завдання 6

In [56]:
coeff = np.array([[1, 1, 2, 3],
                  [3, -1, -2, -2],
                  [2, -3, -1, -1],
                  [1, 2, 3, -1]])

In [57]:
constants = np.array([1, -4, -6, -4])

In [58]:
result = np.linalg.solve(coeff, constants)

In [60]:
for i, x in enumerate(result, start=1):
    print(f"x{i} = {x:.2f}")

x1 = -1.06
x2 = 1.39
x3 = -1.50
x4 = 1.22
